version: "3"
services:
  frontend:
    build: frontend/
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/frontend/src
    networks:
      - rede-virtual-1
  backend:
    build: backend/
    restart: always
    ports:
      - 3001:3001
    environment:
      - DB_HOST=database
    depends_on:
      - database
    networks:
      - rede-virtual-1
      - rede-virtual-2
  database:
    image: betrybe/docker-compose-example-database:v1
    restart: always
    networks:
      - rede-virtual-2
  volumes:
    dados-do-banco:
  networks:
    rede-virtual-1:
    rede-virtual-2:


# version: '3'
# services:
#   frontend:
#     build: frontend/    # Especificamos o contexto, ou seja, a pasta onde está o Dockerfile.
#     restart: on-failure    # Especificamos a política de restart do container.
#     ports:
#       - "3000:3000"     # Mapeamos a porta 3000 do container para a porta 3000 da máquina.
#   backend:
#     build: backend/     # Mesmo caso aqui.
#     restart: on-failure    # Mesmo caso aqui.
#     ports:
#       - "3000:3001"     # Mesmo caso aqui.
#       #  primeiro parâmetro é sempre a porta do computador local e o segundo parâmetro é a porta exposta no container.
#     environment:
#       - DB_HOST=database
#     depends_on:
#       - database
#   database:
#     image: betrybe/docker-compose-example-database:v1    # Especificamos a Imagem Docker diretamente.
#     restart: on-failure    # Mesmo caso aqui.