FROM betrybe/figtrybe-artify:latest
ENTRYPOINT [ "node", "app.js" ]
CMD [ "#VQV Trybe" ]

# docker container run figtrybe-artify -f Ghost "VQV TRYBE"
# docker container run --rm figtrybe-artify "Go Trybe"
# docker container run --rm figtrybe-artify -f Ghost "#VQV TRYBE"